---

# Get Java version String (eg: 11.0.9, 1.8.0_181)
- name: "({{ ansible_distribution }}) DOCKER::Initialize - Check current JAVA version."
  command: >
    java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
    warn=no
  changed_when: false
  failed_when: false
  check_mode: false
  register: java_installed_version
