---

- name: "({{ ansible_distribution }}) DOCKER::Compose - Role Installs Compose for Community Edition"
  block:

   - name: "({{ ansible_distribution }}) DOCKER::Compose - Download and Install Compose script file"
     get_url:
      url: "{{ docker_compose_url }}"
      dest: "/usr/local/bin/docker-compose"
      checksum: "{{ docker_compose_checksum }}"
      mode: u=rwx,g=rx,o=rx

   - name: "({{ ansible_distribution }}) DOCKER::Compose - Create Symlink on Compose Script"
     file:
      src: "/usr/local/bin/docker-compose"
      dest: "/usr/bin/docker-compose"
      state: link

  when:
   - community_edition|bool
   - docker_install_compose|bool
