---

# Include Main Variables
- name: "({{ ansible_distribution }}) KEYCLOAK::Main - Include Variables"
  include_vars: "../vars/main.yml"
  tags: keycloak

# Include OS Release Specific Variables (From the most precise to the family precedence)
- name: "({{ ansible_distribution }}) KEYCLOAK::Main - Include release Specific Variables"
  include_vars: "{{ lookup('first_found', _params) }}"
  vars:
    _params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "../vars"
  ignore_errors: true
  tags: keycloak

  # Include Initialize tasks (Linux)
- name: "({{ ansible_distribution }}) KEYCLOAK::Main - Include Initialize Tasks"
  include_tasks: "initialize.yml"

  # Include Checks Tasks (Linux)
- name: "({{ ansible_distribution }}) KEYCLOAK::Main - Include Checks Tasks"
  include_tasks: "checks.yml"

  # Include Downloads Tasks (Linux)
- name: "({{ ansible_distribution }}) KEYCLOAK::Main - Include Downloads Tasks"
  include_tasks: "downloads.yml"

  # Include Install Tasks (Linux)
- name: "({{ ansible_distribution }}) KEYCLOAK::Main - Include Install Tasks"
  include_tasks: "install.yml"

  # Include Secure Tasks (Linux)
- name: "({{ ansible_distribution }}) KEYCLOAK::Main - Include Secure Tasks"
  include_tasks: "secure.yml"

# Include Startup Tasks (Linux)
- name: "({{ ansible_distribution }}) KEYCLOAK::Main - Include Startup Tasks"
  include_tasks: "startup.yml"

# Include Configure Tasks (Linux)
- name: "({{ ansible_distribution }}) KEYCLOAK::Main - Include Configure Tasks"
  include_tasks: "configure.yml"
