---

# Create Keycloak Admin User for Standalone Mode
- name: "({{ ansible_distribution }}) KEYCLOAK::Secure - Create Keycloak Admin user for Standalone Mode"
  shell: >
   {{ keycloak_home_dir }}/bin/add-user-keycloak.sh -r master -u {{ keycloak_admin_user }} -p {{ keycloak_admin_password }} &&
   touch {{ keycloak_home_dir }}/.mgmt-users-keycloak.{{ keycloak_admin_user }}.created
  args:
   creates: "{{ keycloak_home_dir }}/.mgmt-users-keycloak.{{ keycloak_admin_user }}.created"
  when:
   - keycloak_standalone_mode|bool
  notify:
   - restart keycloak