---

# Handler execution order is related to handler file declaration (not task fired order)

# Rebuild Home Dir Ownership
- name: rebuild home ownership
  file:
   path: "{{ keycloak_home_dir }}"
   owner: "{{ keycloak_os_user }}"
   group: "{{ keycloak_os_group }}"
   recurse: true
   mode: "0750"
   state: "directory"

# Rebuild Module Dir Ownership
- name: rebuild module ownership
  file:
   path: "{{ _keycloak_module_base_path }}"
   owner: "{{ keycloak_os_user }}"
   group: "{{ keycloak_os_group }}"
   recurse: true
   mode: "0750"
   state: "directory"

# Rebuild Data Dir Ownership
- name: rebuild data ownership
  file:
   path: "{{ keycloak_data_dir }}"
   owner: "{{ keycloak_os_user }}"
   group: "{{ keycloak_os_group }}"
   recurse: true
   mode: "0750"
   state: "directory"

# Rebuild Log Dir Ownership
- name: rebuild log ownership
  file:
   path: "{{ keycloak_log_dir }}"
   owner: "{{ keycloak_os_user }}"
   group: "{{ keycloak_os_group }}"
   recurse: true
   mode: "0750"
   state: "directory"

# Rebuild Config Dir Ownership
- name: rebuild config ownership
  file:
   path: "{{ keycloak_config_dir }}"
   owner: "{{ keycloak_os_user }}"
   group: "{{ keycloak_os_group }}"
   recurse: true
   mode: "0750"
   state: "directory"

# Restart Keycloak Service
- name: restart keycloak
  service:
   name: keycloak
   state: restarted

# Flush All Handlers
- meta: flush_handlers
